// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_3-qp5MAf8KrWZxG1KBZNPetj6ugJiM',
    appId: '1:320884749566:web:12c5142b9f4d9ed4f821af',
    messagingSenderId: '320884749566',
    projectId: 'adlicity-sherif',
    authDomain: 'adlicity-sherif.firebaseapp.com',
    storageBucket: 'adlicity-sherif.appspot.com',
    measurementId: 'G-67SHL8NPQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR0TWExwwpbg4Uiag9ILL5kx9g1zOoTuM',
    appId: '1:320884749566:android:9a2ee99bf06151dbf821af',
    messagingSenderId: '320884749566',
    projectId: 'adlicity-sherif',
    storageBucket: 'adlicity-sherif.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi_OFrim6Crd3z19QF47XxX80if8grNsk',
    appId: '1:320884749566:ios:efa09adcb34a2c41f821af',
    messagingSenderId: '320884749566',
    projectId: 'adlicity-sherif',
    storageBucket: 'adlicity-sherif.appspot.com',
    iosBundleId: 'com.sherif.adlicity.adlicity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi_OFrim6Crd3z19QF47XxX80if8grNsk',
    appId: '1:320884749566:ios:efa09adcb34a2c41f821af',
    messagingSenderId: '320884749566',
    projectId: 'adlicity-sherif',
    storageBucket: 'adlicity-sherif.appspot.com',
    iosBundleId: 'com.sherif.adlicity.adlicity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb_3-qp5MAf8KrWZxG1KBZNPetj6ugJiM',
    appId: '1:320884749566:web:558228c3c72b303cf821af',
    messagingSenderId: '320884749566',
    projectId: 'adlicity-sherif',
    authDomain: 'adlicity-sherif.firebaseapp.com',
    storageBucket: 'adlicity-sherif.appspot.com',
    measurementId: 'G-KSPKYZ9FSV',
  );
}
